swagger: '2.0'
tags:
  - name: Test API Swagger
get:
  description: None
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error
parameters:
  - name: name
    in: query
    type: string
    example: budi
  - name: nomerhp
    in: query
    type: string
    example: 0851